package egain.oassdk.docs;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ArrayNode;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import egain.oassdk.core.exceptions.GenerationException;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;

/**
 * Generates Redocly configuration files for proper documentation generation
 * <p>
 * This class creates Redocly configuration files that enable:
 * - Custom themes and styling
 * - API grouping and organization
 * - Code samples and examples
 * - Custom plugins and extensions
 * - Multi-API documentation support
 */
public class RedoclyConfigGenerator {

    private final ObjectMapper objectMapper;

    public RedoclyConfigGenerator() {
        this.objectMapper = new ObjectMapper();
        this.objectMapper.registerModule(new JavaTimeModule());
    }

    /**
     * Generate Redocly configuration
     *
     * @param spec        OpenAPI specification
     * @param outputDir   Output directory for configuration files
     * @param themeConfig Theme configuration
     * @param apiConfig   API-specific configuration
     * @throws GenerationException if generation fails
     */
    public void generateRedoclyConfig(Map<String, Object> spec, String outputDir,
                                      RedoclyThemeConfig themeConfig,
                                      RedoclyApiConfig apiConfig) throws GenerationException {
        if (outputDir == null) {
            throw new IllegalArgumentException("Output directory cannot be null");
        }
        try {
            Files.createDirectories(Paths.get(outputDir));

            // Generate redocly.yaml configuration
            generateRedoclyYaml(spec, outputDir, themeConfig, apiConfig);

            // Generate redocly.json configuration
            generateRedoclyJson(spec, outputDir, themeConfig, apiConfig);

            // Generate theme files
            generateThemeFiles(outputDir, themeConfig);

            // Generate custom CSS
            generateCustomCSS(outputDir, themeConfig);

            // Generate package.json for Redocly
            generatePackageJson(outputDir);

        } catch (Exception e) {
            throw new GenerationException("Failed to generate Redocly configuration: " + e.getMessage(), e);
        }
    }

    /**
     * Generate redocly.yaml configuration file
     */
    private void generateRedoclyYaml(Map<String, Object> spec, String outputDir,
                                     RedoclyThemeConfig themeConfig,
                                     RedoclyApiConfig apiConfig) throws IOException {
        String apiTitle = getAPITitle(spec);
        String apiVersion = getAPIVersion(spec);

        String redoclyYaml = String.format("""
                        apis:
                          main:
                            root: openapi.yaml
                            title: "%s"
                            version: "%s"
                            description: "API Documentation generated by OAS SDK"
                        
                        theme:
                          openapi:
                            theme:
                              colors:
                                primary:
                                  main: "%s"
                                text:
                                  primary: "%s"
                                background:
                                  default: "%s"
                              typography:
                                fontSize: "%s"
                                lineHeight: "%s"
                                fontFamily: "%s"
                                headings:
                                  fontFamily: "%s"
                                  fontWeight: "%s"
                                code:
                                  fontSize: "%s"
                                  fontFamily: "%s"
                                  backgroundColor: "%s"
                              sidebar:
                                backgroundColor: "%s"
                                textColor: "%s"
                                activeTextColor: "%s"
                              rightPanel:
                                backgroundColor: "%s"
                                textColor: "%s"
                              codeBlock:
                                backgroundColor: "%s"
                        
                        lint:
                          extends:
                            - recommended
                          rules:
                            no-unresolved-refs: error
                            no-unused-components: warn
                            operation-4xx-response: warn
                            operation-operationId: error
                            operation-summary: error
                            operation-description: warn
                            operation-tags: warn
                            operation-singular-tag: warn
                            path-declarations-must-exist: error
                            path-not-include-query: error
                            path-params-defined: error
                            tag-description: warn
                            info-description: warn
                            info-contact: warn
                            info-license: warn
                            no-path-trailing-slash: error
                            no-identical-paths: error
                            no-ambiguous-paths: error
                            path-excludes-patterns: error
                            operation-2xx-response: warn
                            operation-operationId-unique: error
                            operation-parameters-unique: error
                            operation-singular-tag: warn
                            operation-tags: warn
                            operation-summary: error
                            operation-description: warn
                            operation-operationId: error
                            operation-4xx-response: warn
                            operation-2xx-response: warn
                            operation-operationId-unique: error
                            operation-parameters-unique: error
                            path-declarations-must-exist: error
                            path-not-include-query: error
                            path-params-defined: error
                            tag-description: warn
                            info-description: warn
                            info-contact: warn
                            info-license: warn
                            no-path-trailing-slash: error
                            no-identical-paths: error
                            no-ambiguous-paths: error
                            path-excludes-patterns: error
                        
                        resolve:
                          http:
                            headers:
                              - matches: ".*\\.example\\.com.*"
                                name: "Authorization"
                                envVariable: "AUTH_TOKEN"
                        
                        plugins:
                          - "@redocly/plugin-commonjs"
                          - "@redocly/plugin-json-schema"
                        
                        features:
                          openapi:
                            generateCodeSamples:
                              languages:
                                - lang: "curl"
                                  label: "cURL"
                                - lang: "javascript"
                                  label: "JavaScript"
                                - lang: "python"
                                  label: "Python"
                                - lang: "java"
                                  label: "Java"
                                - lang: "go"
                                  label: "Go"
                                - lang: "csharp"
                                  label: "C#"
                                - lang: "php"
                                  label: "PHP"
                                - lang: "ruby"
                                  label: "Ruby"
                            generateRequestSamples: true
                            generateResponseSamples: true
                            generateWebhooks: true
                            generateWebhooksCodeSamples: true
                            generateWebhooksRequestSamples: true
                            generateWebhooksResponseSamples: true
                        """,
                apiTitle, apiVersion,
                themeConfig.getPrimaryColor(),
                themeConfig.getTextColor(),
                themeConfig.getBackgroundColor(),
                themeConfig.getFontSize(),
                themeConfig.getLineHeight(),
                themeConfig.getFontFamily(),
                themeConfig.getHeadingFontFamily(),
                themeConfig.getHeadingFontWeight(),
                themeConfig.getCodeFontSize(),
                themeConfig.getCodeFontFamily(),
                themeConfig.getCodeBackgroundColor(),
                themeConfig.getSidebarBackgroundColor(),
                themeConfig.getSidebarTextColor(),
                themeConfig.getSidebarActiveTextColor(),
                themeConfig.getRightPanelBackgroundColor(),
                themeConfig.getRightPanelTextColor(),
                themeConfig.getCodeBlockBackgroundColor()
        );

        Files.write(Paths.get(outputDir, "redocly.yaml"), redoclyYaml.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate redocly.json configuration file
     */
    private void generateRedoclyJson(Map<String, Object> spec, String outputDir,
                                     RedoclyThemeConfig themeConfig,
                                     RedoclyApiConfig apiConfig) throws IOException {
        ObjectNode config = objectMapper.createObjectNode();

        // API configuration
        ObjectNode apis = objectMapper.createObjectNode();
        ObjectNode mainApi = objectMapper.createObjectNode();
        mainApi.put("root", "openapi.yaml");
        mainApi.put("title", getAPITitle(spec));
        mainApi.put("version", getAPIVersion(spec));
        mainApi.put("description", "API Documentation generated by OAS SDK");
        apis.set("main", mainApi);
        config.set("apis", apis);

        // Theme configuration
        ObjectNode theme = objectMapper.createObjectNode();
        ObjectNode openapi = objectMapper.createObjectNode();
        ObjectNode themeConfigNode = objectMapper.createObjectNode();

        // Colors
        ObjectNode colors = objectMapper.createObjectNode();
        ObjectNode primary = objectMapper.createObjectNode();
        primary.put("main", themeConfig.getPrimaryColor());
        colors.set("primary", primary);

        ObjectNode text = objectMapper.createObjectNode();
        text.put("primary", themeConfig.getTextColor());
        colors.set("text", text);

        ObjectNode background = objectMapper.createObjectNode();
        background.put("default", themeConfig.getBackgroundColor());
        colors.set("background", background);

        themeConfigNode.set("colors", colors);

        // Typography
        ObjectNode typography = objectMapper.createObjectNode();
        typography.put("fontSize", themeConfig.getFontSize());
        typography.put("lineHeight", themeConfig.getLineHeight());
        typography.put("fontFamily", themeConfig.getFontFamily());

        ObjectNode headings = objectMapper.createObjectNode();
        headings.put("fontFamily", themeConfig.getHeadingFontFamily());
        headings.put("fontWeight", themeConfig.getHeadingFontWeight());
        typography.set("headings", headings);

        ObjectNode code = objectMapper.createObjectNode();
        code.put("fontSize", themeConfig.getCodeFontSize());
        code.put("fontFamily", themeConfig.getCodeFontFamily());
        code.put("backgroundColor", themeConfig.getCodeBackgroundColor());
        typography.set("code", code);

        themeConfigNode.set("typography", typography);

        // Sidebar
        ObjectNode sidebar = objectMapper.createObjectNode();
        sidebar.put("backgroundColor", themeConfig.getSidebarBackgroundColor());
        sidebar.put("textColor", themeConfig.getSidebarTextColor());
        sidebar.put("activeTextColor", themeConfig.getSidebarActiveTextColor());
        themeConfigNode.set("sidebar", sidebar);

        // Right panel
        ObjectNode rightPanel = objectMapper.createObjectNode();
        rightPanel.put("backgroundColor", themeConfig.getRightPanelBackgroundColor());
        rightPanel.put("textColor", themeConfig.getRightPanelTextColor());
        themeConfigNode.set("rightPanel", rightPanel);

        // Code block
        ObjectNode codeBlock = objectMapper.createObjectNode();
        codeBlock.put("backgroundColor", themeConfig.getCodeBlockBackgroundColor());
        themeConfigNode.set("codeBlock", codeBlock);

        openapi.set("theme", themeConfigNode);
        theme.set("openapi", openapi);
        config.set("theme", theme);

        // Lint configuration
        ObjectNode lint = objectMapper.createObjectNode();
        ArrayNode extendsArray = objectMapper.createArrayNode();
        extendsArray.add("recommended");
        lint.set("extends", extendsArray);

        ObjectNode rules = objectMapper.createObjectNode();
        rules.put("no-unresolved-refs", "error");
        rules.put("no-unused-components", "warn");
        rules.put("operation-4xx-response", "warn");
        rules.put("operation-operationId", "error");
        rules.put("operation-summary", "error");
        rules.put("operation-description", "warn");
        rules.put("operation-tags", "warn");
        rules.put("path-declarations-must-exist", "error");
        rules.put("path-not-include-query", "error");
        rules.put("path-params-defined", "error");
        rules.put("tag-description", "warn");
        rules.put("info-description", "warn");
        rules.put("info-contact", "warn");
        rules.put("info-license", "warn");
        rules.put("no-path-trailing-slash", "error");
        rules.put("no-identical-paths", "error");
        rules.put("no-ambiguous-paths", "error");
        rules.put("operation-2xx-response", "warn");
        rules.put("operation-operationId-unique", "error");
        rules.put("operation-parameters-unique", "error");
        lint.set("rules", rules);
        config.set("lint", lint);

        // Resolve configuration
        ObjectNode resolve = objectMapper.createObjectNode();
        ObjectNode http = objectMapper.createObjectNode();
        ArrayNode headers = objectMapper.createArrayNode();
        ObjectNode authHeader = objectMapper.createObjectNode();
        authHeader.put("matches", ".*\\.example\\.com.*");
        authHeader.put("name", "Authorization");
        authHeader.put("envVariable", "AUTH_TOKEN");
        headers.add(authHeader);
        http.set("headers", headers);
        resolve.set("http", http);
        config.set("resolve", resolve);

        // Plugins
        ArrayNode plugins = objectMapper.createArrayNode();
        plugins.add("@redocly/plugin-commonjs");
        plugins.add("@redocly/plugin-json-schema");
        config.set("plugins", plugins);

        // Features
        ObjectNode features = objectMapper.createObjectNode();
        ObjectNode openapiFeatures = objectMapper.createObjectNode();

        ObjectNode generateCodeSamples = objectMapper.createObjectNode();
        ArrayNode languages = objectMapper.createArrayNode();

        String[] codeLanguages = {"curl", "javascript", "python", "java", "go", "csharp", "php", "ruby"};
        String[] codeLabels = {"cURL", "JavaScript", "Python", "Java", "Go", "C#", "PHP", "Ruby"};

        for (int i = 0; i < codeLanguages.length; i++) {
            ObjectNode lang = objectMapper.createObjectNode();
            lang.put("lang", codeLanguages[i]);
            lang.put("label", codeLabels[i]);
            languages.add(lang);
        }

        generateCodeSamples.set("languages", languages);
        openapiFeatures.set("generateCodeSamples", generateCodeSamples);
        openapiFeatures.put("generateRequestSamples", true);
        openapiFeatures.put("generateResponseSamples", true);
        openapiFeatures.put("generateWebhooks", true);
        openapiFeatures.put("generateWebhooksCodeSamples", true);
        openapiFeatures.put("generateWebhooksRequestSamples", true);
        openapiFeatures.put("generateWebhooksResponseSamples", true);

        features.set("openapi", openapiFeatures);
        config.set("features", features);

        Files.write(Paths.get(outputDir, "redocly.json"),
                objectMapper.writerWithDefaultPrettyPrinter().writeValueAsBytes(config));
    }

    /**
     * Generate theme files
     */
    private void generateThemeFiles(String outputDir, RedoclyThemeConfig themeConfig) throws IOException {
        // Generate theme directory
        Files.createDirectories(Paths.get(outputDir, "theme"));

        // Generate custom theme CSS using StringBuilder to avoid String.format issues

        String css = "/* Custom Redocly Theme */\n" +
                ":root {\n" +
                "  --primary-color: " + themeConfig.getPrimaryColor() + ";\n" +
                "  --text-color: " + themeConfig.getTextColor() + ";\n" +
                "  --background-color: " + themeConfig.getBackgroundColor() + ";\n" +
                "  --sidebar-background: " + themeConfig.getSidebarBackgroundColor() + ";\n" +
                "  --sidebar-text: " + themeConfig.getSidebarTextColor() + ";\n" +
                "  --sidebar-active: " + themeConfig.getSidebarActiveTextColor() + ";\n" +
                "  --code-background: " + themeConfig.getCodeBackgroundColor() + ";\n" +
                "  --code-text: " + themeConfig.getTextColor() + ";\n" +
                "}\n\n" +
                "/* Override Redocly styles */\n" +
                ".redoc-wrap {\n" +
                "  font-family: " + themeConfig.getFontFamily() +
                ", -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n" +
                "  font-size: " + themeConfig.getFontSize() + ";\n" +
                "  line-height: " + themeConfig.getLineHeight() + ";\n" +
                "  color: var(--text-color);\n" +
                "  background-color: var(--background-color);\n" +
                "}\n\n" +
                ".redoc-wrap h1, .redoc-wrap h2, .redoc-wrap h3, \n" +
                ".redoc-wrap h4, .redoc-wrap h5, .redoc-wrap h6 {\n" +
                "  font-family: " + themeConfig.getHeadingFontFamily() +
                ", -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n" +
                "  font-weight: " + themeConfig.getHeadingFontWeight() + ";\n" +
                "  color: var(--primary-color);\n" +
                "}\n\n" +
                ".redoc-wrap .sidebar {\n" +
                "  background-color: var(--sidebar-background);\n" +
                "  color: var(--sidebar-text);\n" +
                "}\n\n" +
                ".redoc-wrap .sidebar .menu-item.active {\n" +
                "  color: var(--sidebar-active);\n" +
                "}\n\n" +
                ".redoc-wrap code {\n" +
                "  font-family: " + themeConfig.getCodeFontFamily() +
                ", 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;\n" +
                "  font-size: " + themeConfig.getCodeFontSize() + ";\n" +
                "  background-color: var(--code-background);\n" +
                "  color: var(--code-text);\n" +
                "  padding: 2px 4px;\n" +
                "  border-radius: 3px;\n" +
                "}\n\n" +
                ".redoc-wrap pre code {\n" +
                "  background-color: var(--code-background);\n" +
                "  color: var(--code-text);\n" +
                "  padding: 1rem;\n" +
                "  border-radius: 6px;\n" +
                "  display: block;\n" +
                "  overflow-x: auto;\n" +
                "}\n\n" +
                ".redoc-wrap .right-panel {\n" +
                "  background-color: var(--sidebar-background);\n" +
                "  color: var(--sidebar-text);\n" +
                "}\n\n" +
                "/* Custom button styles */\n" +
                ".redoc-wrap .btn {\n" +
                "  background-color: var(--primary-color);\n" +
                "  color: white;\n" +
                "  border: none;\n" +
                "  padding: 8px 16px;\n" +
                "  border-radius: 4px;\n" +
                "  cursor: pointer;\n" +
                "  transition: background-color 0.2s ease;\n" +
                "}\n\n" +
                ".redoc-wrap .btn:hover {\n" +
                "  background-color: color-mix(in srgb, var(--primary-color) 80%, black);\n" +
                "}\n\n" +
                "/* Custom scrollbar */\n" +
                ".redoc-wrap ::-webkit-scrollbar {\n" +
                "  width: 8px;\n" +
                "}\n\n" +
                ".redoc-wrap ::-webkit-scrollbar-track {\n" +
                "  background: var(--sidebar-background);\n" +
                "}\n\n" +
                ".redoc-wrap ::-webkit-scrollbar-thumb {\n" +
                "  background: var(--primary-color);\n" +
                "  border-radius: 4px;\n" +
                "}\n\n" +
                ".redoc-wrap ::-webkit-scrollbar-thumb:hover {\n" +
                "  background: color-mix(in srgb, var(--primary-color) 80%, black);\n" +
                "}\n";

        Files.write(Paths.get(outputDir, "theme", "custom.css"), css.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate custom CSS file
     */
    private void generateCustomCSS(String outputDir, RedoclyThemeConfig themeConfig) throws IOException {
        // Build CSS using StringBuilder to avoid String.format issues with % characters

        String css = "/* OAS SDK Custom Documentation Styles */\n\n" +

                // Import Google Fonts
                "/* Import Google Fonts */\n" +
                "@import url('https://fonts.googleapis.com/css2?family=" +
                themeConfig.getFontFamily().replace(" ", "+") +
                ":wght@300;400;500;600;700&display=swap');\n" +
                "@import url('https://fonts.googleapis.com/css2?family=" +
                themeConfig.getHeadingFontFamily().replace(" ", "+") +
                ":wght@300;400;500;600;700&display=swap');\n\n" +

                // CSS Variables
                "/* CSS Variables for theming */\n" +
                ":root {\n" +
                "  --oas-primary: " + themeConfig.getPrimaryColor() + ";\n" +
                "  --oas-secondary: " + themeConfig.getSecondaryColor() + ";\n" +
                "  --oas-text: " + themeConfig.getTextColor() + ";\n" +
                "  --oas-background: " + themeConfig.getBackgroundColor() + ";\n" +
                "  --oas-sidebar-bg: " + themeConfig.getSidebarBackgroundColor() + ";\n" +
                "  --oas-sidebar-text: " + themeConfig.getSidebarTextColor() + ";\n" +
                "  --oas-sidebar-active: " + themeConfig.getSidebarActiveTextColor() + ";\n" +
                "  --oas-code-bg: " + themeConfig.getCodeBackgroundColor() + ";\n" +
                "  --oas-code-text: " + themeConfig.getCodeTextColor() + ";\n" +
                "  --oas-border: " + themeConfig.getBorderColor() + ";\n" +
                "  --oas-shadow: " + themeConfig.getShadowColor() + ";\n" +
                "}\n\n" +

                // Base styles
                "/* Base styles */\n" +
                "body {\n" +
                "  font-family: '" + themeConfig.getFontFamily() +
                "', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n" +
                "  font-size: " + themeConfig.getFontSize() + ";\n" +
                "  line-height: " + themeConfig.getLineHeight() + ";\n" +
                "  color: var(--oas-text);\n" +
                "  background-color: var(--oas-background);\n" +
                "  margin: 0;\n" +
                "  padding: 0;\n" +
                "}\n\n" +

                // Typography
                "/* Typography */\n" +
                "h1, h2, h3, h4, h5, h6 {\n" +
                "  font-family: '" + themeConfig.getHeadingFontFamily() +
                "', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;\n" +
                "  font-weight: " + themeConfig.getHeadingFontWeight() + ";\n" +
                "  color: var(--oas-primary);\n" +
                "  margin-top: 0;\n" +
                "  margin-bottom: 1rem;\n" +
                "}\n\n" +
                "h1 { font-size: 2.5rem; }\n" +
                "h2 { font-size: 2rem; }\n" +
                "h3 { font-size: 1.75rem; }\n" +
                "h4 { font-size: 1.5rem; }\n" +
                "h5 { font-size: 1.25rem; }\n" +
                "h6 { font-size: 1rem; }\n\n" +

                // Code styles
                "/* Code styles */\n" +
                "code {\n" +
                "  font-family: '" + themeConfig.getCodeFontFamily() +
                "', 'Monaco', 'Menlo', 'Ubuntu Mono', monospace;\n" +
                "  font-size: " + themeConfig.getCodeFontSize() + ";\n" +
                "  background-color: var(--oas-code-bg);\n" +
                "  color: var(--oas-code-text);\n" +
                "  padding: 0.2em 0.4em;\n" +
                "  border-radius: 3px;\n" +
                "  border: 1px solid var(--oas-border);\n" +
                "}\n\n" +
                "pre {\n" +
                "  background-color: var(--oas-code-bg);\n" +
                "  color: var(--oas-code-text);\n" +
                "  padding: 1rem;\n" +
                "  border-radius: 6px;\n" +
                "  border: 1px solid var(--oas-border);\n" +
                "  overflow-x: auto;\n" +
                "  margin: 1rem 0;\n" +
                "}\n\n" +
                "pre code {\n" +
                "  background: none;\n" +
                "  padding: 0;\n" +
                "  border: none;\n" +
                "  border-radius: 0;\n" +
                "}\n\n" +

                // Button styles
                "/* Button styles */\n" +
                ".btn {\n" +
                "  display: inline-block;\n" +
                "  padding: 0.5rem 1rem;\n" +
                "  background-color: var(--oas-primary);\n" +
                "  color: white;\n" +
                "  text-decoration: none;\n" +
                "  border-radius: 4px;\n" +
                "  border: none;\n" +
                "  cursor: pointer;\n" +
                "  font-size: 0.9rem;\n" +
                "  font-weight: 500;\n" +
                "  transition: all 0.2s ease;\n" +
                "  box-shadow: 0 2px 4px var(--oas-shadow);\n" +
                "}\n\n" +
                ".btn:hover {\n" +
                "  background-color: color-mix(in srgb, var(--oas-primary) 85%, black);\n" +
                "  transform: translateY(-1px);\n" +
                "  box-shadow: 0 4px 8px var(--oas-shadow);\n" +
                "}\n\n" +
                ".btn:active {\n" +
                "  transform: translateY(0);\n" +
                "  box-shadow: 0 2px 4px var(--oas-shadow);\n" +
                "}\n\n" +
                ".btn-secondary {\n" +
                "  background-color: var(--oas-secondary);\n" +
                "}\n\n" +
                ".btn-outline {\n" +
                "  background-color: transparent;\n" +
                "  color: var(--oas-primary);\n" +
                "  border: 2px solid var(--oas-primary);\n" +
                "}\n\n" +
                ".btn-outline:hover {\n" +
                "  background-color: var(--oas-primary);\n" +
                "  color: white;\n" +
                "}\n\n" +

                // Card styles
                "/* Card styles */\n" +
                ".card {\n" +
                "  background: white;\n" +
                "  border-radius: 8px;\n" +
                "  box-shadow: 0 2px 8px var(--oas-shadow);\n" +
                "  padding: 1.5rem;\n" +
                "  margin: 1rem 0;\n" +
                "  border: 1px solid var(--oas-border);\n" +
                "}\n\n" +
                ".card-header {\n" +
                "  border-bottom: 1px solid var(--oas-border);\n" +
                "  padding-bottom: 1rem;\n" +
                "  margin-bottom: 1rem;\n" +
                "}\n\n" +
                ".card-title {\n" +
                "  margin: 0;\n" +
                "  color: var(--oas-primary);\n" +
                "}\n\n" +

                // Layout styles
                "/* Layout styles */\n" +
                ".container {\n" +
                "  max-width: 1200px;\n" +
                "  margin: 0 auto;\n" +
                "  padding: 0 1rem;\n" +
                "}\n\n" +
                ".row {\n" +
                "  display: flex;\n" +
                "  flex-wrap: wrap;\n" +
                "  margin: 0 -0.5rem;\n" +
                "}\n\n" +
                ".col {\n" +
                "  flex: 1;\n" +
                "  padding: 0 0.5rem;\n" +
                "}\n\n" +

                // Responsive design
                "/* Responsive design */\n" +
                "@media (max-width: 768px) {\n" +
                "  .row {\n" +
                "    flex-direction: column;\n" +
                "  }\n" +
                "  .col {\n" +
                "    flex: none;\n" +
                "    width: 100%;\n" +
                "  }\n" +
                "  h1 { font-size: 2rem; }\n" +
                "  h2 { font-size: 1.75rem; }\n" +
                "  h3 { font-size: 1.5rem; }\n" +
                "}\n\n" +

                // Utility classes
                "/* Utility classes */\n" +
                ".text-center { text-align: center; }\n" +
                ".text-left { text-align: left; }\n" +
                ".text-right { text-align: right; }\n\n" +
                ".mt-1 { margin-top: 0.25rem; }\n" +
                ".mt-2 { margin-top: 0.5rem; }\n" +
                ".mt-3 { margin-top: 1rem; }\n" +
                ".mt-4 { margin-top: 1.5rem; }\n" +
                ".mt-5 { margin-top: 3rem; }\n\n" +
                ".mb-1 { margin-bottom: 0.25rem; }\n" +
                ".mb-2 { margin-bottom: 0.5rem; }\n" +
                ".mb-3 { margin-bottom: 1rem; }\n" +
                ".mb-4 { margin-bottom: 1.5rem; }\n" +
                ".mb-5 { margin-bottom: 3rem; }\n\n" +
                ".p-1 { padding: 0.25rem; }\n" +
                ".p-2 { padding: 0.5rem; }\n" +
                ".p-3 { padding: 1rem; }\n" +
                ".p-4 { padding: 1.5rem; }\n" +
                ".p-5 { padding: 3rem; }\n";

        Files.write(Paths.get(outputDir, "custom.css"), css.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate package.json for Redocly dependencies
     */
    private void generatePackageJson(String outputDir) throws IOException {
        String packageJson = """
                {
                  "name": "oas-sdk-documentation",
                  "version": "1.0.0",
                  "description": "API Documentation generated by OAS SDK",
                  "main": "index.js",
                  "scripts": {
                    "build": "redocly build-docs openapi.yaml --output index.html --theme.openapi.theme.colors.primary.main='#32329f'",
                    "serve": "redocly preview-docs openapi.yaml --port 8081",
                    "lint": "redocly lint openapi.yaml",
                    "bundle": "redocly bundle openapi.yaml --output bundled.yaml",
                    "split": "redocly split openapi.yaml --outDir split",
                    "join": "redocly join openapi.yaml --outDir joined",
                    "validate": "redocly validate openapi.yaml"
                  },
                  "dependencies": {
                    "@redocly/cli": "^1.0.0",
                    "@redocly/plugin-commonjs": "^1.0.0",
                    "@redocly/plugin-json-schema": "^1.0.0"
                  },
                  "devDependencies": {
                    "redoc-cli": "^0.13.21"
                  },
                  "keywords": [
                    "openapi",
                    "redocly",
                    "documentation",
                    "api",
                    "oas-sdk"
                  ],
                  "author": "OAS SDK Team",
                  "license": "MIT"
                }
                """;

        Files.write(Paths.get(outputDir, "package.json"), packageJson.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Helper methods
     */
    private String getAPITitle(Map<String, Object> spec) {
        Map<String, Object> info = egain.oassdk.Util.asStringObjectMap(spec.get("info"));
        return info != null ? (String) info.get("title") : "API";
    }

    private String getAPIVersion(Map<String, Object> spec) {
        Map<String, Object> info = egain.oassdk.Util.asStringObjectMap(spec.get("info"));
        return info != null ? (String) info.get("version") : "1.0.0";
    }

    /**
     * Configuration classes for Redocly theming
     */
    public static class RedoclyThemeConfig {
        private String primaryColor = "#32329f";
        private String secondaryColor = "#6c757d";
        private String textColor = "#333333";
        private String backgroundColor = "#ffffff";
        private String sidebarBackgroundColor = "#f8f9fa";
        private String sidebarTextColor = "#495057";
        private String sidebarActiveTextColor = "#32329f";
        private String rightPanelBackgroundColor = "#f8f9fa";
        private String rightPanelTextColor = "#495057";
        private String codeBackgroundColor = "#f8f9fa";
        private String codeTextColor = "#e83e8c";
        private String borderColor = "#dee2e6";
        private String shadowColor = "rgba(0, 0, 0, 0.1)";
        private String fontSize = "14px";
        private String lineHeight = "1.5em";
        private String fontFamily = "Inter";
        private String headingFontFamily = "Inter";
        private String headingFontWeight = "600";
        private String codeFontSize = "13px";
        private String codeFontFamily = "JetBrains Mono";

        // Getters and setters
        public String getPrimaryColor() {
            return primaryColor;
        }

        public void setPrimaryColor(String primaryColor) {
            this.primaryColor = primaryColor;
        }

        public String getSecondaryColor() {
            return secondaryColor;
        }

        public void setSecondaryColor(String secondaryColor) {
            this.secondaryColor = secondaryColor;
        }

        public String getTextColor() {
            return textColor;
        }

        public void setTextColor(String textColor) {
            this.textColor = textColor;
        }

        public String getBackgroundColor() {
            return backgroundColor;
        }

        public void setBackgroundColor(String backgroundColor) {
            this.backgroundColor = backgroundColor;
        }

        public String getSidebarBackgroundColor() {
            return sidebarBackgroundColor;
        }

        public void setSidebarBackgroundColor(String sidebarBackgroundColor) {
            this.sidebarBackgroundColor = sidebarBackgroundColor;
        }

        public String getSidebarTextColor() {
            return sidebarTextColor;
        }

        public void setSidebarTextColor(String sidebarTextColor) {
            this.sidebarTextColor = sidebarTextColor;
        }

        public String getSidebarActiveTextColor() {
            return sidebarActiveTextColor;
        }

        public void setSidebarActiveTextColor(String sidebarActiveTextColor) {
            this.sidebarActiveTextColor = sidebarActiveTextColor;
        }

        public String getRightPanelBackgroundColor() {
            return rightPanelBackgroundColor;
        }

        public void setRightPanelBackgroundColor(String rightPanelBackgroundColor) {
            this.rightPanelBackgroundColor = rightPanelBackgroundColor;
        }

        public String getRightPanelTextColor() {
            return rightPanelTextColor;
        }

        public void setRightPanelTextColor(String rightPanelTextColor) {
            this.rightPanelTextColor = rightPanelTextColor;
        }

        public String getCodeBackgroundColor() {
            return codeBackgroundColor;
        }

        public void setCodeBackgroundColor(String codeBackgroundColor) {
            this.codeBackgroundColor = codeBackgroundColor;
        }

        public String getCodeTextColor() {
            return codeTextColor;
        }

        public void setCodeTextColor(String codeTextColor) {
            this.codeTextColor = codeTextColor;
        }

        public String getBorderColor() {
            return borderColor;
        }

        public void setBorderColor(String borderColor) {
            this.borderColor = borderColor;
        }

        public String getShadowColor() {
            return shadowColor;
        }

        public void setShadowColor(String shadowColor) {
            this.shadowColor = shadowColor;
        }

        public String getFontSize() {
            return fontSize;
        }

        public void setFontSize(String fontSize) {
            this.fontSize = fontSize;
        }

        public String getLineHeight() {
            return lineHeight;
        }

        public void setLineHeight(String lineHeight) {
            this.lineHeight = lineHeight;
        }

        public String getFontFamily() {
            return fontFamily;
        }

        public void setFontFamily(String fontFamily) {
            this.fontFamily = fontFamily;
        }

        public String getHeadingFontFamily() {
            return headingFontFamily;
        }

        public void setHeadingFontFamily(String headingFontFamily) {
            this.headingFontFamily = headingFontFamily;
        }

        public String getHeadingFontWeight() {
            return headingFontWeight;
        }

        public void setHeadingFontWeight(String headingFontWeight) {
            this.headingFontWeight = headingFontWeight;
        }

        public String getCodeFontSize() {
            return codeFontSize;
        }

        public void setCodeFontSize(String codeFontSize) {
            this.codeFontSize = codeFontSize;
        }

        public String getCodeFontFamily() {
            return codeFontFamily;
        }

        public void setCodeFontFamily(String codeFontFamily) {
            this.codeFontFamily = codeFontFamily;
        }

        public String getCodeBlockBackgroundColor() {
            return codeBackgroundColor;
        }

        public void setCodeBlockBackgroundColor(String codeBlockBackgroundColor) {
            this.codeBackgroundColor = codeBlockBackgroundColor;
        }
    }

    public static class RedoclyApiConfig {
        private boolean generateCodeSamples = true;
        private boolean generateRequestSamples = true;
        private boolean generateResponseSamples = true;
        private boolean generateWebhooks = true;
        private String[] codeLanguages = {"curl", "javascript", "python", "java", "go", "csharp", "php", "ruby"};
        private String[] codeLabels = {"cURL", "JavaScript", "Python", "Java", "Go", "C#", "PHP", "Ruby"};

        // Getters and setters
        public boolean isGenerateCodeSamples() {
            return generateCodeSamples;
        }

        public void setGenerateCodeSamples(boolean generateCodeSamples) {
            this.generateCodeSamples = generateCodeSamples;
        }

        public boolean isGenerateRequestSamples() {
            return generateRequestSamples;
        }

        public void setGenerateRequestSamples(boolean generateRequestSamples) {
            this.generateRequestSamples = generateRequestSamples;
        }

        public boolean isGenerateResponseSamples() {
            return generateResponseSamples;
        }

        public void setGenerateResponseSamples(boolean generateResponseSamples) {
            this.generateResponseSamples = generateResponseSamples;
        }

        public boolean isGenerateWebhooks() {
            return generateWebhooks;
        }

        public void setGenerateWebhooks(boolean generateWebhooks) {
            this.generateWebhooks = generateWebhooks;
        }

        public String[] getCodeLanguages() {
            return codeLanguages != null ? codeLanguages.clone() : null;
        }

        public void setCodeLanguages(String[] codeLanguages) {
            this.codeLanguages = codeLanguages != null ? codeLanguages.clone() : null;
        }

        public String[] getCodeLabels() {
            return codeLabels != null ? codeLabels.clone() : null;
        }

        public void setCodeLabels(String[] codeLabels) {
            this.codeLabels = codeLabels != null ? codeLabels.clone() : null;
        }
    }
}
