package egain.oassdk.dev.docs;

import egain.oassdk.Util;
import egain.oassdk.core.exceptions.GenerationException;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.util.Map;

/**
 * Generates Redocly documentation
 */
public class RedoclyGenerator {

    /**
     * Generate Redocly documentation
     *
     * @param spec      OpenAPI specification
     * @param outputDir Output directory
     * @throws GenerationException if generation fails
     */
    public void generateDocumentation(Map<String, Object> spec, String outputDir) throws GenerationException {
        if (outputDir == null) {
            throw new IllegalArgumentException("Output directory cannot be null");
        }
        try {
            Files.createDirectories(Paths.get(outputDir));

            // Generate Redocly HTML
            generateRedoclyHTML(spec, outputDir);

            // Generate Redocly configuration
            generateRedoclyConfig(spec, outputDir);

            // Generate package.json
            generatePackageJson(spec, outputDir);

            // Generate build scripts
            generateBuildScripts(spec, outputDir);

            // Generate Docker configuration
            generateDockerConfig(spec, outputDir);

        } catch (Exception e) {
            throw new GenerationException("Failed to generate Redocly documentation: " + e.getMessage(), e);
        }
    }

    /**
     * Generate Redocly HTML
     */
    private void generateRedoclyHTML(Map<String, Object> spec, String outputDir) throws IOException {
        String apiTitle = getAPITitle(spec);

        String html = String.format("""
                <!DOCTYPE html>
                <html>
                <head>
                    <title>%s API Documentation</title>
                    <meta charset="utf-8"/>
                    <meta name="viewport" content="width=device-width, initial-scale=1">
                    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,700|Roboto:300,400,700" rel="stylesheet">
                    <style>
                        body {
                            margin: 0;
                            padding: 0;
                        }
                    </style>
                </head>
                <body>
                    <redoc spec-url='openapi.yaml'></redoc>
                    <script src="https://cdn.redoc.ly/redoc/latest/bundles/redoc.standalone.js"></script>
                </body>
                </html>
                """, apiTitle);

        Files.write(Paths.get(outputDir, "index.html"), html.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate Redocly configuration
     */
    private void generateRedoclyConfig(Map<String, Object> spec, String outputDir) throws IOException {
        String config = """
                {
                  "theme": {
                    "colors": {
                      "primary": {
                        "main": "#32329f"
                      }
                    },
                    "typography": {
                      "fontSize": "14px",
                      "lineHeight": "1.5em",
                      "code": {
                        "fontSize": "13px"
                      }
                    }
                  },
                  "sidebar": {
                    "backgroundColor": "#fafafa"
                  }
                }
                """;

        Files.write(Paths.get(outputDir, "redocly.json"), config.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate package.json
     */
    private void generatePackageJson(Map<String, Object> spec, String outputDir) throws IOException {
        String packageJson = """
                {
                  "name": "api-documentation",
                  "version": "1.0.0",
                  "description": "API Documentation generated with Redocly",
                  "main": "index.html",
                  "scripts": {
                    "build": "redocly build-docs openapi.yaml --output index.html",
                    "serve": "redocly preview-docs openapi.yaml --port 8081",
                    "lint": "redocly lint openapi.yaml",
                    "bundle": "redocly bundle openapi.yaml --output bundled.yaml"
                  },
                  "devDependencies": {
                    "@redocly/cli": "^1.0.0"
                  },
                  "keywords": [
                    "api",
                    "documentation",
                    "redocly",
                    "openapi"
                  ],
                  "author": "Generated by OAS SDK",
                  "license": "MIT"
                }
                """;

        Files.write(Paths.get(outputDir, "package.json"), packageJson.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate build scripts
     */
    private void generateBuildScripts(Map<String, Object> spec, String outputDir) throws IOException {
        // Generate build script
        String buildScript = """
                #!/bin/bash
                
                echo "Building Redocly documentation..."
                
                # Install dependencies
                if [ ! -d "node_modules" ]; then
                    echo "Installing dependencies..."
                    npm install
                fi
                
                # Build documentation
                echo "Building documentation..."
                npm run build
                
                echo "Documentation built successfully!"
                echo "Open index.html in your browser to view the documentation."
                """;

        Files.write(Paths.get(outputDir, "build.sh"), buildScript.getBytes(StandardCharsets.UTF_8));

        // Generate serve script
        String serveScript = """
                #!/bin/bash
                
                echo "Starting Redocly documentation server..."
                
                # Install dependencies
                if [ ! -d "node_modules" ]; then
                    echo "Installing dependencies..."
                    npm install
                fi
                
                # Serve documentation
                echo "Starting server at http://localhost:8081"
                npm run serve
                """;

        Files.write(Paths.get(outputDir, "serve.sh"), serveScript.getBytes(StandardCharsets.UTF_8));

        // Generate Docker build script
        String dockerBuildScript = """
                #!/bin/bash
                
                echo "Building Docker image for documentation..."
                
                # Build Docker image
                docker build -t api-docs .
                
                echo "Docker image built successfully!"
                echo "Run with: docker run -p 8080:80 api-docs"
                """;

        Files.write(Paths.get(outputDir, "docker-build.sh"), dockerBuildScript.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Generate Docker configuration
     */
    private void generateDockerConfig(Map<String, Object> spec, String outputDir) throws IOException {
        // Generate Dockerfile
        String dockerfile = """
                FROM nginx:alpine
                
                # Copy documentation files
                COPY index.html /usr/share/nginx/html/
                COPY openapi.yaml /usr/share/nginx/html/
                COPY redocly.json /usr/share/nginx/html/
                
                # Configure nginx
                RUN echo 'server { \\
                    listen 80; \\
                    server_name localhost; \\
                    location / { \\
                        root /usr/share/nginx/html; \\
                        index index.html; \\
                    } \\
                }' > /etc/nginx/conf.d/default.conf
                
                EXPOSE 80
                
                CMD ["nginx", "-g", "daemon off;"]
                """;

        Files.write(Paths.get(outputDir, "Dockerfile"), dockerfile.getBytes(StandardCharsets.UTF_8));

        // Generate docker-compose.yml
        String dockerCompose = """
                version: '3.8'
                
                services:
                  docs:
                    build: .
                    ports:
                      - "8080:80"
                    volumes:
                      - ./openapi.yaml:/usr/share/nginx/html/openapi.yaml:ro
                    restart: unless-stopped
                """;

        Files.write(Paths.get(outputDir, "docker-compose.yml"), dockerCompose.getBytes(StandardCharsets.UTF_8));
    }

    /**
     * Helper methods
     */
    private String getAPITitle(Map<String, Object> spec) {
        Map<String, Object> info = Util.asStringObjectMap(spec.get("info"));
        return info != null ? (String) info.get("title") : "API";
    }
}
